version: '3.1'

services:
  dev1:
    image: python:3.11.2-slim-buster
    environment:
      - TZ=America/New_York
    volumes:
      - '.:/code'
    working_dir: /code
    tty: true
    stdin_open: true
    command: bash